### ISSUE TITLE
Indexing custom components

### ISSUE THREAD

**Issue by skartknet** [skybrud/Skybrud.Umbraco.GridData.Dtge#3]
Hi, I can't find any updated documentation about how to index my custom grid components.

I have tried creating a new `GridConverter` that uses new models for `GridControleDtageValue` but it getting really complicated and I wonder if there's a simpler way of doing this.

On your docs you talk about  _`GridConverterBase` now contains a virtual `TryGetSearchableText`_ but it doesn't.

Can you please let me know the best solution for this? Thanks!

**Comment by abjerner** [comment]
Hi @skartknet 

The examples may be a little outdated, as this has changed over past major releases.

The right approach is still to implement your own grid converter, but instead you need to override the `TryWriteSearchableText` method like shown in the example below.

There is still a `TryGetSearchableText` method, but this calls `TryWriteSearchableText`, which is why it's the correct method to override.

In your PR, you had overriden the `GetSearchableText.GetSearchableText`. This was the correct method to override i Umbraco 8),    but as the main grid package has changed since U8, the method didn't get called by the main grid package. Overriding `GetSearchableText.WriteSearchableText` instead ensures the methods gets called correctly.

The reason for changing this from U8 to U9 is that the `TryWriteSearchableText` and `WriteSearchableText` methods internally writes to a `TextWriter`, which is more efficient.

Anyways, when implementing your custom grid converter, you can override the `TryWriteSearchableText(GridContext, IPublishedElement, TextWriter)` method. The general idea is that when the grid tries to write the searchable text for a DTGE value, this method will automatically be called.

The grid doesn't know how your custom element types should be indexed, but you can handle different element types using a switch case like in my example below, and then do something different for each element type:

```csharp
using System.IO;
using System.Text.RegularExpressions;
using Skybrud.Umbraco.GridData;
using Skybrud.Umbraco.GridData.Composers;
using Skybrud.Umbraco.GridData.Converters;
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.Models.PublishedContent;
using Vive.Models.Umbraco.Elements;

namespace web {

    internal class IndexGridElementComposer : IComposer {

        public void Compose(IUmbracoBuilder builder) {

            builder.GridConverters().Append<IndexGridElementConverter>();
        }

    }

    internal class IndexGridElementConverter : GridConverterBase {

        public override bool TryWriteSearchableText(GridContext context, IPublishedElement element, TextWriter writer) {

            switch (element) {

                case BlockQuote quote:
                    writer.WriteLine(quote.Quote);
                    writer.WriteLine(quote.Byline);
                    return true;

                case BlockTabularData table:
                    if (table.Data is null) return false;
                    foreach (var row in table.Data.Cells) {
                        foreach (var cell in row) {
                            writer.WriteLine(Regex.Replace(cell.Value, "<.*?>", " "));
                        }
                    }
                    return true;

            }

            return false;

        }

    }

}
```
